version: 2

sources:
  - name: rawdata_dbt
    database: case_study
    schema: rawdata
    tables:
      - name: charging_stations
      - name: motor_vehicle_register
      - name: area_name
      - name: area_population
      - name: area_territory

  - name: cleaning_dbt
    database: case_study
    schema: dbt_sha_cleaned
    tables:
      - name: area_info
      - name: clean_ev_vehicle
      - name: parsed_charging_stations

  - name: geo_dbt
    database: GEOGRAPHY__BOUNDARIES__INSIGHTS__NEW_ZEALAND__FREE
    schema: NZ_GEOGRAPHY_FREE
    tables:
      - name: SUBURB_AND_LOCALITIES